### PR TITLE
Revert "Log script load errors properly"

### PR DESCRIPTION
**Pull request by wheresrhys**
Reverts Financial-Times/o-comment-utilities#1

After reading up more on script error handling, I don't think this will work, but I still don't think  these errors should end up getting passed to oErrors (I'm not sure if that's done in o-comments or in next)

### CODE REVIEW

**Comment by wheresrhys** [comment]
@roland-vachter

**Comment by roland-vachter** [comment]
It is done in o-comments. If you think it shouldn't be pushed to oErrors, then I can exclude them.

**Comment by wheresrhys** [comment]
In general I don't think network errors are very useful to send to oErrors, so I would either include an option to exclude them, or just exclude them

**Comment by roland-vachter** [comment]
Ok, I will exclude them. Also, handling errors for JSONP is not very robust in the browsers either, so basically you can't distinguish network error or something else, especially in IEs.
So yes, I will exclude them.

**Comment by roland-vachter** [comment]
I'm not sure what should be sent explicitly to oErrors. Could you give me examples?

**Comment by wheresrhys** [comment]
Broadly speaking, we try to exclude network errors; as it's the web these are inevitable and there's nothing we can do about them. Other than that we send most errors to oErrors

**Pull request merged**
