### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-comment-utilities bundle size difference from 2.4.0 to b76e259cdfd9073e4647f5f6eb98edd18aef8d15
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-comment-utilities bundle size difference from 2.4.0 to d9d7e08cff8276c0d8ed30cfc3d85a42e5e888dc
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-comment-utilities bundle size difference from 2.4.0 to d35ffe6010467c4edd3438c4828f9d422a251e7b
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-comment-utilities bundle size difference from 2.4.0 to 4ea21fc4f49dfed8c2d35164ddb42b75deaaadeb
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Pull request merged**
